module.exports = {
  COUNTRIES: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegowina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo, the Democratic Republic of the",
    "Cook Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia (Hrvatska)",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "France Metropolitan",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard and Mc Donald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran (Islamic Republic of)",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People's Republic of",
    "Korea, Republic of",
    "Kuwait",
    "Kyrgyzstan",
    "Lao, People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia, The Former Yugoslav Republic of",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova, Republic of",
    "Monaco",
    "Mongolia",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia (Slovak Republic)",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "Spain",
    "Sri Lanka",
    "St. Helena",
    "St. Pierre and Miquelon",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen Islands",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan, Province of China",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Virgin Islands (British)",
    "Virgin Islands (U.S.)",
    "Wallis and Futuna Islands",
    "Western Sahara",
    "Yemen",
    "Yugoslavia",
    "Zambia",
    "Zimbabwe",
  ],
  ENT_CIVILITIES: [
    "",
    "EI- ENTREPRISE INDIVIDUELLE",
    "SARL- Société à responsabilité limitée",
    "SA- Société Anonyme",
    "SNC- Société en Nom Collectif",
    "SCS- Société en Commandite Simple",
    "SP- Société en participation",
    "SF- Société de fait",
    "GIE- Groupement d’Intérêt Economique ",
    "ONG- Organisation non gouvernementale",
    "ETC- Etablissement",
  ],
  PERS_CIVILITIES: ["", "Mme- madame", "Mlle- mademoiselle", "M.- monsieur"],
  CONTRAT_TYPE: [
    {
      title: "CDI",
      value: "l0",
    },
    {
      title: "CDD",
      value: "l1",
    },
    {
      title: "Intérim",
      value: "l2",
    },
    {
      title: "Stage",
      value: "l3",
    },
    {
      title: "Freelance",
      value: "l4",
    },
    {
      title: "Alternance",
      value: "l5",
    },
    {
      title: "Temps partiel",
      value: "l5",
    },
    {
      title: "Statutaire",
      value: "l5",
    },
  ].map((mes) => mes.title),
  LEVELS: ["l0", "l1", "l2", "l3", "4", "l5", "l6", "l7", "l8", "l9"],
  EXPERIENCE_LEVEL: [
    "Etudiant, jeune diplômé",
    "Etudiant, jeune diplômé",
    "Débutant < 2 ans",
    "Expérience entre 2 ans et 5 ans",
    "Expérience entre 5 ans et 10 ans",
    "Expérience > 10 ans",
  ],
  STUDIES_LEVEL: [
    "Bac",
    "Bac+1",
    "Bac+2",
    "Bac+3",
    "Bac+4",
    "Bac+5",
    "Qualification avant bac",
    "Bac+5 et plus",
  ],
  CONSTANT: {
    CategoryCoursePageSize: 20,
    UserTablePageSize: 60,
    BlogPageSize: 10,
    COURSE_CORVER_IMAGE_MAX_SIZE: 100000000,
    COURSE_LESON_VIDEO_MAX_SIZE: 100000000,
    QUIZZ_PERCENTAGE: 50,
    L_MOB_C_OVERVIE_SECTION: 5,
    L_MOB_C_OVERVIE_COMMENTS: 4,
  },
  STRINGS: {
    small_pass: "Mot de passe trop court (6 lettres minimum)",
    small_username: "nom d'utilisateur trop court (6 lettres minimum) ",
    small_displayname: "nom public trop court (6 lettres minimum) ",
    long_displayname: "nom public trop long (50 lettres maximun)",
    long_username: "nom d'utilisateur trop long (50 lettres maximun)",
    recquired_username: "nom d'utilisateur recquis",
    small_firstname: "Nom trop court (6 lettres minimum) ",
    small_lastname: "Prénom trop court (6 lettres minimum) ",
    long_firstname: "Nom trop long (50 lettres maximun)",
    long_lastname: "Prénom trop long (50 lettres maximun)",
    not_url: "addresse url invalide",
    not_mail: "addresse e-mail invalide",
    recquired_pass: "mot de passe recquis",
    recquired_companyname: "Vous devez indiquer le nom de l'entreprise",
    recquired_companydes: "Donnez une petite desscription de votre entreprise",
    recquired_companyacti: "Vous devez choisir un secteur d'activité",
    recquired_country: "vous devez Selectinner un pays",
    recquired_city: "vous devez saisir une ville",
    recquired_phone1: "Vous devez saisir un numéro de télephone",
    recquired_candidate_title: "Dites-en sur votre titre",
    recquired_oftitle: "Donnez un titre à votre nouvelle offre",
    recquired_ofdesc: "Donnez une description à votre nouvelle offre",
    recquired_sheduledOferWothoutDate: "Définissez Le programme de votre offre",
    recquired_profdesc: "Décrivez le profil recherché",
    recquired_ofstudie: "Vous n'avez spécifié aucun niveau d'Etude",
    recquired_ofexperience: "Vous n'avez spécifié aucune expérience",
    recquired_zip: "Zip code est requis",
    long_companyacti: "vous pouvez choisir jusqu'à 6 secteurs d'activité",
    min_offeracti: "vous devez indiquer un secteur !",
    long_offeracti: "vous pouvez choisir jusqu'à 2 catégories d'activité",
    incorect_user_or_pass: "Addresse E-mail ou mot de passe incorrect !",
    already_taken_username:
      "Addresse E-mail indisponible. choisissez un autre ",
    already_formator_processed: "Vous avez déjà soumis une demande",
    unexisted_user: "utilisateur introuvable .",
    blocked_user: "utilisateur Bloqué. contactez le Support",
    already_taken_mail: "addresse e-mail indisponible. choisissez un autre ",
    succesfully_signup: "Inscription reuissi . redirection à la page d'accueil",
    succesfully_formator_requested: "Dossier Bien reçu. Analyse en cour !",
    succesfully_passresset:
      "Vous devriez bientôt recevoir un e-mail vous permettant de réinitialiser votre mot de passe. Assurez-vous de vérifier vos spams et votre corbeille si vous ne trouvez pas l'e-mail.",
    succesfully_signout:
      "Déconnexion reuissi . redirection à la page d'accueil",
    succesfully_passchange:
      "Changement de mot de passe reuissi ! Connectez vous .",
    Ocurred_error: "An error occured",
    bad_pass: "Mot de passe incorrecte",
    incorect_file_size: "Taille de fichier incorrect",
    incorect_file_type: "Type de fichier incorrect",
    invalid_message: "Message invalid",
    invalid_object: "objet invalid",
    /**courses*/
    invalid_course_name: "titre du cour non permis",
    invalid_course_category: "categorie de cour non permise",
    invalid_course_date: "date non permise",
    invalid_course_duration: "durée non permise",
    constrain_string_size: (li, si) =>
      `Doit respecter la contrainte de taille des caractères : ${li}: ${si}`,
  },

  COOKIE_DURATIONN: {
    TOKEN_AUTHENTICATE: 5184000000,
  },
};
