module.exports = {
  CONSTANT: {
    CategoryCoursePageSize: 20,
    UserTablePageSize: 60,
    BlogPageSize: 10,
    COURSE_CORVER_IMAGE_MAX_SIZE: 100000000,
    COURSE_LESON_VIDEO_MAX_SIZE: 100000000,
    QUIZZ_PERCENTAGE: 50,
    L_MOB_C_OVERVIE_SECTION: 5,
    L_MOB_C_OVERVIE_COMMENTS: 4,
  },
  STRINGS: {
    small_pass: "Mot de passe trop court (6 lettres minimum)",
    small_username: "nom d'utilisateur trop court (6 lettres minimum) ",
    small_displayname: "nom public trop court (6 lettres minimum) ",
    long_displayname: "nom public trop long (50 lettres maximun)",
    long_username: "nom d'utilisateur trop long (50 lettres maximun)",
    recquired_username: "nom d'utilisateur recquis",
    small_firstname: "Nom trop court (6 lettres minimum) ",
    small_lastname: "Prénom trop court (6 lettres minimum) ",
    long_firstname: "Nom trop long (50 lettres maximun)",
    long_lastname: "Prénom trop long (50 lettres maximun)",
    not_url: "addresse url invalide",
    not_mail: "addresse e-mail invalide",
    recquired_pass: "mot de passe recquis",
    recquired_companyname: "Vous devez indiquer le nom de l'entreprise",
    recquired_companydes: "Donnez une petite desscription de votre entreprise",
    recquired_companyacti: "Vous devez choisir un secteur d'activité",
    recquired_country: "vous devez Selectinner un pays",
    recquired_city: "vous devez saisir une ville",
    unfound_fields: "Un ou plusieurs champs sont manquants !",
    recquired_phone1: "Vous devez saisir un numéro de télephone",
    recquired_candidate_title: "Dites-en sur votre titre",
    recquired_oftitle: "Donnez un titre à votre nouvelle offre",
    recquired_ofdesc: "Donnez une description à votre nouvelle offre",
    recquired_sheduledOferWothoutDate: "Définissez Le programme de votre offre",
    recquired_profdesc: "Décrivez le profil recherché",
    recquired_ofstudie: "Vous n'avez spécifié aucun niveau d'Etude",
    recquired_ofexperience: "Vous n'avez spécifié aucune expérience",
    recquired_zip: "Zip code est requis",
    long_companyacti: "vous pouvez choisir jusqu'à 6 secteurs d'activité",
    min_offeracti: "vous devez indiquer un secteur !",
    long_offeracti: "vous pouvez choisir jusqu'à 2 catégories d'activité",
    incorect_user_or_pass: "Addresse E-mail ou mot de passe incorrect !",
    already_taken_username:
      "Addresse E-mail indisponible. choisissez un autre ",
    already_formator_processed: "Vous avez déjà soumis une demande",
    unexisted_user: "utilisateur introuvable .",
    blocked_user: "utilisateur Bloqué. contactez le Support",
    already_taken_mail: "addresse e-mail indisponible. choisissez un autre ",
    succesfully_signup: "Inscription reuissi . redirection à la page d'accueil",
    succesfully_formator_requested: "Dossier Bien reçu. Analyse en cour !",
    succesfully_passresset:
      "Vous devriez bientôt recevoir un e-mail vous permettant de réinitialiser votre mot de passe. Assurez-vous de vérifier vos spams et votre corbeille si vous ne trouvez pas l'e-mail.",
    succesfully_signout:
      "Déconnexion reuissi . redirection à la page d'accueil",
    succesfully_passchange:
      "Changement de mot de passe reuissi ! Connectez vous .",
    Ocurred_error: "An error occured",
    bad_pass: "Mot de passe incorrecte",
    incorect_file_size: "Taille de fichier incorrect",
    incorect_file_type: "Type de fichier incorrect",
    invalid_message: "Message invalid",
    invalid_object: "objet invalid",
    /**courses*/
    invalid_course_name: "titre du cour non permis",
    invalid_course_category: "categorie de cour non permise",
    invalid_course_date: "date non permise",
    invalid_course_duration: "durée non permise",
    constrain_string_size: (li, si) =>
      `Doit respecter la contrainte de taille des caractères : ${li}: ${si}`,
  },

  COOKIE_DURATIONN: {
    TOKEN_AUTHENTICATE: 5184000000,
  },
};
