module.exports = {
  ContactMessage: {
    username: "",
    objet: "",
    message: "",
    user_email: "",
  },
  User: {
    user_email: "",
    user_pass: "",
    identity: "",
    visibility: "review",
    user_type: "",
    user_status: 1,
    user_registered: new Date(Date.now()).toISOString(),
    last_connected: new Date(Date.now()).toISOString(),
  },
  Application: {
    ID: 1,
    userId: 1,
    targetID: 1,
    title: "",
    description: "",
    offer: {},
    targetDelete: false,
    file: "",
    response: {
      decision: "",
      date: null,
    },
    post_date: new Date(Date.now()).toISOString(),
  },
  Demand: {
    ID: 1,
    userId: 1,
    targetID: 1,
    offerID: 1,
    offer: {},
    targetDelete: false,
    offer_title: "",
    message: "",
    companyname: "",
    response: {
      decision: "",
      date: null,
    },
    post_date: new Date(Date.now()).toISOString(),
  },
};
